### ISSUE TITLE
Non-quiet, non-verbose mode should output pretty strings

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomicapp#186] opened 2015-07-23 14:40 UTC
By default atomic app run with no args should output strings for humans that do not have timestamps, log levels, etc. Currently we're getting all INFO logs, which is a lot.

Current output:

```
# atomicapp run /atomicapp
2015-07-23 14:37:22,084 - atomicapp.utils - INFO - atomicapp.status.info.message=All artifacts OK.
2015-07-23 14:37:22,084 - atomicapp.nulecule_base - INFO - Artifacts for aggregated-mariadb-atomicapp present for these providers:
2015-07-23 14:37:22,084 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/openshift/volume.yaml: OK.
2015-07-23 14:37:22,084 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/openshift/service.yaml: OK.
2015-07-23 14:37:22,085 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/openshift/pod.yaml: OK.
2015-07-23 14:37:22,085 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/kubernetes/wordpress-pod.yaml: OK.
2015-07-23 14:37:22,085 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/kubernetes/wordpress-service.yaml: OK.
2015-07-23 14:37:22,085 - atomicapp.utils - INFO - atomicapp.status.info.message=All artifacts OK.
2015-07-23 14:37:22,085 - atomicapp.nulecule_base - INFO - Artifacts for wordpress present for these providers: openshift, kubernetes
2015-07-23 14:37:22,086 - atomicapp.run - WARNING - Setting image to projectatomic/mariadb-centos7-atomicapp
2015-07-23 14:37:22,087 - atomicapp.install - INFO - App name is projectatomic/mariadb-centos7-atomicapp, will be populated to /atomicapp/external/aggregated-mariadb-atomicapp
2015-07-23 14:37:22,087 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading app projectatomic/mariadb-centos7-atomicapp .
2015-07-23 14:37:22,089 - atomicapp.utils - INFO - atomicapp.status.answer.message={"mariadb-app": {"db_pass": "pass", "image": "fedora/mariadb", "db_name": "name", "db_user": "user"}, "general": {"openshiftconfig": "/host/home/cloud-user/.kube/config", "namespace": "default", "provider": "openshift"}}
2015-07-23 14:37:24,127 - atomicapp.utils - INFO - atomicapp.status.info.message=Pulling image projectatomic/mariadb-centos7-atomicapp ...
Trying to pull repository registry.access.redhat.com/projectatomic/mariadb-centos7-atomicapp ... not found
latest: Pulling from docker.io/projectatomic/mariadb-centos7-atomicapp
045f82560154: Pull complete
...
269c050a3679: Already exists
Digest: sha256:5d252b342859adfc265c46f11ec1da1314e3fcc5a901f63241c0fec3d49686a9
Status: Downloaded newer image for docker.io/projectatomic/mariadb-centos7-atomicapp:latest
cb9e82d98a64196ffe85cbc0fe05a1a60db0117eab67fd25dba551b1aae2e51f
2015-07-23 14:37:33,780 - atomicapp.utils - INFO - Using temporary directory /tmp/nulecule-8u8Z7k
2015-07-23 14:37:34,361 - atomicapp.utils - INFO - atomicapp.status.info.message=Copied app successfully.
mariadb-centos7-atomicapp-WbVuNZ
2015-07-23 14:37:34,476 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading app_id mariadb-atomicapp .
2015-07-23 14:37:34,493 - atomicapp.utils - INFO - atomicapp.status.info.message=Checking all artifacts
2015-07-23 14:37:34,493 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/docker/mariadb-app-pod_run: OK.
2015-07-23 14:37:34,494 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/kubernetes/mariadb-pod.yaml: OK.
2015-07-23 14:37:34,494 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/kubernetes/mariadb-service.yaml: OK.
2015-07-23 14:37:34,494 - atomicapp.utils - INFO - atomicapp.status.info.message=All artifacts OK.
2015-07-23 14:37:34,494 - atomicapp.nulecule_base - INFO - Artifacts for mariadb-atomicapp present for these providers: docker, kubernetes, openshift
2015-07-23 14:37:34,494 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading Nulecule file.
2015-07-23 14:37:34,495 - atomicapp.install - INFO - Installing dependencies for mariadb-atomicapp
2015-07-23 14:37:34,495 - atomicapp.utils - INFO - atomicapp.status.info.message=All dependencies installed successfully.
2015-07-23 14:37:34,495 - atomicapp.utils - INFO - atomicapp.status.answer.message={"mariadb-app": {"db_pass": "pass", "image": "fedora/mariadb", "db_name": "name", "db_user": "user"}, "mariadb-atomicapp": {"db_pass": null, "db_name": null, "root_pass": "MySQLPass", "db_user": null}, "general": {"openshiftconfig": "/host/home/cloud-user/.kube/config", "namespace": "default", "provider": "openshift"}}
2015-07-23 14:37:34,495 - atomicapp.utils - INFO - atomicapp.status.info.message=Install Successful.
2015-07-23 14:37:34,496 - atomicapp.utils - INFO - atomicapp.status.info.message=Install Successful.
2015-07-23 14:37:34,515 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/docker/mariadb-app-pod_run: OK.
2015-07-23 14:37:34,515 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/kubernetes/mariadb-pod.yaml: OK.
2015-07-23 14:37:34,515 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://artifacts/kubernetes/mariadb-service.yaml: OK.
2015-07-23 14:37:34,516 - atomicapp.utils - INFO - atomicapp.status.info.message=All artifacts OK.
2015-07-23 14:37:34,516 - atomicapp.nulecule_base - INFO - Artifacts for mariadb-atomicapp present for these providers: docker, kubernetes, openshift
2015-07-23 14:37:34,516 - atomicapp.utils - INFO - atomicapp.status.error.message=db_user is missing in answers.conf .
db_user (Database User): user
2015-07-23 14:38:02,086 - atomicapp.utils - INFO - atomicapp.status.error.message=db_pass is missing in answers.conf .
db_pass (Database Password): pass
2015-07-23 14:38:08,416 - atomicapp.utils - INFO - atomicapp.status.error.message=db_name is missing in answers.conf .
db_name (Database Name): name
2015-07-23 14:38:16,058 - atomicapp.utils - INFO - atomicapp.status.info.message=Deploying component mariadb-atomicapp ...
2015-07-23 14:38:16,058 - atomicapp.run - INFO - Using provider openshift for component mariadb-atomicapp
```

**Comment by goern** [comment] 2015-07-24 13:19
see #134

**Comment by vpavlin** [comment] 2015-07-29 11:00
Yes..and maybe we should have one parameter which would turn on the output added for cockpit

**Comment by vpavlin** [comment] 2015-09-03 13:30
In my opinion, we should add second logging handler which will log to a file. This one can have level set to INFO and thus produce valuable information for development and debugging. 

Second part of this would be to introduce new argument (`--machine-readable`?) which would turn the machine readable output on.

That would enable us to keep the output clear for normal user but still provide an easy way to debug and integrate with external tools.

**Comment by charliedrage** [comment] 2015-09-03 14:24
+1 for another argument. or even if it's -v (verbose) which would be the machine readable logging and then -vv (very verbose) for all that nitty gritty dev logging.

**Comment by cdrage** [comment] 2015-11-25 14:33
Duplicate of #134.

Working on this in PR #415

**Closed by cdrage** 2015-11-25 14:33 UTC
Labels: component:core, enhancement, need_doc
