### ISSUE TITLE
atomicapp unable to find Nulecule file

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#194] opened 2015-08-07 08:26 UTC
this is observed here: https://github.com/projectatomic/nulecule/issues/141

```
$ sudo atomic install projectatomic/wordpress-centos7-atomicapp
docker run --rm -it --privileged -v /run:/run -v `pwd`:/atomicapp -e IMAGE=projectatomic/wordpress-centos7-atomicapp -e NAME=wordpress-centos7-atomicapp --name wordpress-centos7-atomicapp projectatomic/wordpress-centos7-atomicapp -v install --destination /atomicapp /application-entity
2015-08-07 08:25:08,989 - atomicapp.install - INFO - App path is /application-entity, will be populated to /atomicapp
2015-08-07 08:25:09,014 - atomicapp.nulecule_base - DEBUG - Setting app id to wordpress-atomicapp
2015-08-07 08:25:09,014 - atomicapp.install - DEBUG - Setting path to /application-entity
2015-08-07 08:25:09,014 - atomicapp.install - INFO - Copying content of directory /application-entity to /atomicapp
2015-08-07 08:25:09,014 - atomicapp.install - INFO - Copying app wordpress-centos7-atomicapp
2015-08-07 08:25:09,029 - atomicapp.install - INFO - Component data exist in /atomicapp, skipping population...
2015-08-07 08:25:09,029 - atomicapp.nulecule_base - DEBUG - Version check successful: specversion == 0.0.2
2015-08-07 08:25:09,029 - atomicapp.nulecule_base - DEBUG - No artifacts for aggregated-mariadb-atomicapp
2015-08-07 08:25:09,029 - atomicapp.nulecule_base - INFO - Artifacts for aggregated-mariadb-atomicapp present for these providers: 
2015-08-07 08:25:09,029 - atomicapp.nulecule_base - DEBUG - Provider: openshift
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - DEBUG - Artifact file://artifacts/openshift/volume.yaml: OK
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - DEBUG - Artifact file://artifacts/openshift/service.yaml: OK
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - DEBUG - Artifact file://artifacts/openshift/pod.yaml: OK
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - DEBUG - Provider: kubernetes
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - DEBUG - Artifact file://artifacts/kubernetes/wordpress-pod.yaml: OK
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - DEBUG - Artifact file://artifacts/kubernetes/wordpress-service.yaml: OK
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - INFO - Artifacts for wordpress present for these providers: openshift, kubernetes
2015-08-07 08:25:09,030 - atomicapp.install - INFO - Installing dependencies for wordpress-atomicapp
2015-08-07 08:25:09,030 - atomicapp.utils - DEBUG - {u'source': u'docker://projectatomic/mariadb-centos7-atomicapp', u'name': u'aggregated-mariadb-atomicapp'}
2015-08-07 08:25:09,030 - atomicapp.install - INFO - Component aggregated-mariadb-atomicapp is external dependency
2015-08-07 08:25:09,030 - atomicapp.install - DEBUG - Component path: /atomicapp/external/aggregated-mariadb-atomicapp
2015-08-07 08:25:09,030 - atomicapp.install - INFO - Pulling projectatomic/mariadb-centos7-atomicapp
2015-08-07 08:25:09,030 - atomicapp.install - INFO - App name is projectatomic/mariadb-centos7-atomicapp, will be populated to /atomicapp/external/aggregated-mariadb-atomicapp
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - DEBUG - Data given {'general': {'namespace': 'default', 'provider': 'kubernetes'}}
2015-08-07 08:25:09,030 - atomicapp.nulecule_base - DEBUG - {'namespace': 'default', 'provider': 'kubernetes'}
2015-08-07 08:25:09,762 - atomicapp.nulecule_base - DEBUG - Output of docker images cmd: 
latest: Pulling from docker.io/projectatomic/mariadb-centos7-atomicapp
f1b10cd84249: Already exists 
c852f6d61e65: Already exists 
7322fbe74aa5: Already exists 
b9e8df520b94: Already exists 
36873d767517: Already exists 
a71d35ab23d4: Already exists 
300fdceaf673: Already exists 
358243682dfa: Already exists 
06697d00bbd3: Already exists 
96925fa4ee9e: Already exists 
ed0a83cfde70: Already exists 
276001559a51: Already exists 
593794fa9ab7: Already exists 
d258dd3252f0: Already exists 
aeea42f054c6: Already exists 
db828900997a: Already exists 
269c050a3679: Already exists 
b20942ce794a: Already exists 
e7909023ba36: Already exists 
b5f344dd74ff: Already exists 
fd7322d5aa4b: Already exists 
0377b3fcb39c: Already exists 
Digest: sha256:681a174d0366643bc7b46a33b2b9b6fef79c1a80e714cf2e760c937522bb689a
Status: Image is up to date for docker.io/projectatomic/mariadb-centos7-atomicapp:latest
2015-08-07 08:25:13,864 - atomicapp.nulecule_base - DEBUG - {'namespace': 'default', 'provider': 'kubernetes'}
2015-08-07 08:25:13,865 - atomicapp.install - DEBUG - Creating a container with name mariadb-centos7-atomicapp-AYreQt
7065a5a6a3c2936f4330e3f703d685e52ffb3d8aaa98edf7325fc506b0a72f63
2015-08-07 08:25:20,649 - atomicapp.utils - INFO - Using temporary directory /tmp/nulecule-Ols2lv
2015-08-07 08:25:20,649 - atomicapp.install - DEBUG - ['docker', 'cp', u'mariadb-centos7-atomicapp-AYreQt:/application-entity', '/tmp/nulecule-Ols2lv']
FATA[0000] Error response from daemon: Could not find the file /application-entity in container mariadb-centos7-atomicapp-AYreQt 
mariadb-centos7-atomicapp-AYreQt
2015-08-07 08:25:21,619 - atomicapp.install - DEBUG - Nulecule path for pulled image: /tmp/nulecule-Ols2lv/application-entity/Nulecule
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 89, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 70, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 17, in cli_install
    install.install()
  File "/usr/lib/python2.7/site-packages/atomicapp/install.py", line 114, in install
    values = self._installDependencies()
  File "/usr/lib/python2.7/site-packages/atomicapp/install.py", line 147, in _installDependencies
    values = Utils.update(values, component_app.install())
  File "/usr/lib/python2.7/site-packages/atomicapp/install.py", line 98, in install
    self.nulecule_base.loadMainfile(mainfile_path)
  File "/usr/lib/python2.7/site-packages/atomicapp/nulecule_base.py", line 88, in loadMainfile
    raise Exception("%s not found: %s" % (MAIN_FILE, path))
Exception: Nulecule not found: /tmp/nulecule-Ols2lv/application-entity/Nulecule

[goern@rh-t540p-goern-example-com tmp.LORrLis0GO]$ 
```

**Comment by aweiteka** [comment] 2015-08-08 02:22
This might have been introduced in docker 1.7, now shipping in fedora. Centos is still on docker 1.6.

@dustymabe was looking at the docker cp cmd. Is this the same error you were seeing?

**Comment by aweiteka** [comment] 2015-08-11 14:59
Can we confirm this is a dupe of #205 ?

**Comment by sub-mod** [comment] 2015-08-11 16:43
facing issues with docker 1.7.x from long time
atomicapp doesnt work with 1.7.1
faced another issue some time back https://github.com/projectatomic/atomicapp/issues/174

**Comment by dustymabe** [comment] 2015-08-11 21:18
@aweiteka looks like the same issue as #205 to me. If we want to reference the upstream bug here and close #205 as a dup then that is fine with me.

**Comment by kbsingh** [comment] 2015-08-13 15:26
Hitting the same thing with a completely updated centos7 system : 

Status: Image is up to date for docker.io/projectatomic/helloapache:latest
2015-08-13 15:24:04,125 - atomicapp.nulecule_base - DEBUG - {u'provider': u'kubernetes'}
2015-08-13 15:24:04,125 - atomicapp.install - DEBUG - Creating a container with name helloapache-RbEucP
c382e1db75b57ef9ab60f8b2be55900a8ddad984a4891520fc8a9d47c664df12
2015-08-13 15:24:04,941 - atomicapp.utils - INFO - Using temporary directory /tmp/nulecule-ytjr4e
2015-08-13 15:24:04,941 - atomicapp.install - DEBUG - ['docker', 'cp', 'helloapache-RbEucP:/application-entity', '/tmp/nulecule-ytjr4e']
FATA[0000] Error response from daemon: Could not find the file /application-entity in container helloapache-RbEucP 
helloapache-RbEucP
2015-08-13 15:24:09,104 - atomicapp.install - DEBUG - Nulecule path for pulled image: /tmp/nulecule-ytjr4e/application-entity/Nulecule
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 89, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 70, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 20, in cli_run
    ae = Run(**vars(args))
  File "/usr/lib/python2.7/site-packages/atomicapp/run.py", line 64, in __init__
    install.install()
  File "/usr/lib/python2.7/site-packages/atomicapp/install.py", line 98, in install
    self.nulecule_base.loadMainfile(mainfile_path)
  File "/usr/lib/python2.7/site-packages/atomicapp/nulecule_base.py", line 88, in loadMainfile
    raise Exception("%s not found: %s" % (MAIN_FILE, path))
Exception: Nulecule not found: /tmp/nulecule-ytjr4e/application-entity/Nulecule


cc @ggallen

**Comment by jasonbrooks** [comment] 2015-08-13 17:14
I see the same thing as @kbsingh -- I am able to run the helloapache app w/ 1.7.1, but I must first atomic install, and then atomic run works. I ran it w/ another VM w/ Docker version 1.6.2, build ba1f6c3/1.6.2, and that works w/o the install step.

**Comment by sub-mod** [comment] 2015-08-13 18:08
@kbsingh @jasonbrooks fyi... in f22 there is a new rpm available which works with atomicapp

**Closed** 2015-08-14 17:14 UTC
Labels: bug
