### ISSUE TITLE
Only one openshift template artifact processed

### ISSUE THREAD

**Issue by markllama** [projectatomic/atomicapp#358] opened 2015-10-26 14:03 UTC
When running an app with the OpenShift provider, if the app has more than one artifact (template), then only one is executed.

Debug logs indicate both are _processed_ but only a single __oc__ command is executed and only the components defined in them are created.

When the containers defined are combined in a single template, then the entire app is created.  If the containers are defined in two different templates, only one is created.

Sample: 
    https://github.com/markllama/openshift3mlbparks/tree/nulecule-two-templates

**Comment by markllama** [comment] 2015-10-26 14:04
Note that both templates are "processed" but only the results from the second template are noted in the output from the oc command at the bottom.

```
atomic run markllama/mlbparks-app  2>&1 | tee atomic-run.log
docker run -it --rm  --privileged -v /home/bos/mlamouri/openshift3mlbparks:/atomicapp -v /run:/run -v /:/host --net=host --name mlbparks-app -e NAME=mlbparks-app -e IMAGE=markllama/mlbparks-app markllama/mlbparks-app -v  run  /atomicapp
2015-10-26 13:49:58,141 - atomicapp.install - INFO - App name is markllama/mlbparks-app, will be populated to /atomicapp
2015-10-26 13:49:58,141 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading app markllama/mlbparks-app .
2015-10-26 13:49:58,141 - atomicapp.nulecule_base - DEBUG - Path to answers file given, loading /atomicapp/answers.conf
2015-10-26 13:49:58,142 - atomicapp.utils - INFO - atomicapp.status.answer.message={"general": {"providerconfig": "/home/bos/mlamouri/.kube/config", "provider": "openshift"}}
2015-10-26 13:49:58,143 - atomicapp.nulecule_base - DEBUG - {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}
2015-10-26 13:49:58,291 - atomicapp.nulecule_base - DEBUG - Output of docker images cmd: 9e36ea709317

2015-10-26 13:49:58,291 - atomicapp.nulecule_base - DEBUG - Image markllama/mlbparks-app already present with id 9e36ea709317. Use --update to re-pull.
2015-10-26 13:49:58,291 - atomicapp.nulecule_base - DEBUG - {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}
2015-10-26 13:49:58,292 - atomicapp.install - DEBUG - Creating a container with name mlbparks-app-cab71857097d
2015-10-26 13:49:58,292 - atomicapp.install - DEBUG - /usr/bin/docker run --name mlbparks-app-cab71857097d --entrypoint /bin/true markllama/mlbparks-app
2015-10-26 13:49:59,904 - atomicapp.utils - INFO - Using temporary directory /tmp/nulecule-fphW4b
2015-10-26 13:49:59,904 - atomicapp.install - DEBUG - ['/usr/bin/docker', 'cp', 'mlbparks-app-cab71857097d:/application-entity', '/tmp/nulecule-fphW4b']
2015-10-26 13:50:00,260 - atomicapp.install - DEBUG - Application entity data copied to /tmp/nulecule-fphW4b
2015-10-26 13:50:00,260 - atomicapp.utils - INFO - atomicapp.status.info.message=Copied app successfully.
mlbparks-app-cab71857097d
2015-10-26 13:50:02,664 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading app_id mlbparks-app .
2015-10-26 13:50:02,672 - atomicapp.nulecule_base - DEBUG - Setting app id to mlbparks-app
2015-10-26 13:50:02,672 - atomicapp.install - DEBUG - Nulecule path for pulled image: /tmp/nulecule-fphW4b/application-entity/Nulecule
2015-10-26 13:50:02,672 - atomicapp.install - DEBUG - App ID: mlbparks-app
2015-10-26 13:50:02,672 - atomicapp.nulecule_base - DEBUG - Version check successful: specversion == 0.0.2
2015-10-26 13:50:02,672 - atomicapp.utils - INFO - atomicapp.status.info.message=Checking all artifacts
2015-10-26 13:50:02,672 - atomicapp.nulecule_base - DEBUG - Provider: openshift
2015-10-26 13:50:02,673 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://mongodb-template.json: OK.
2015-10-26 13:50:02,673 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://mlbparks-app-template.json: OK.
2015-10-26 13:50:02,673 - atomicapp.utils - INFO - atomicapp.status.info.message=All artifacts OK. 
2015-10-26 13:50:02,673 - atomicapp.nulecule_base - INFO - Artifacts for mlbparks-app present for these providers: openshift
2015-10-26 13:50:02,673 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading Nulecule file.
2015-10-26 13:50:02,673 - atomicapp.install - INFO - Installing dependencies for mlbparks-app
2015-10-26 13:50:02,673 - atomicapp.utils - DEBUG - {u'artifacts': {u'openshift': [u'file://mongodb-template.json', u'file://mlbparks-app-template.json']}, u'name': u'mlbparks-app'}
2015-10-26 13:50:02,674 - atomicapp.nulecule_base - DEBUG - Param providerconfig already in general with value /home/bos/mlamouri/.kube/config
2015-10-26 13:50:02,674 - atomicapp.nulecule_base - DEBUG - Param provider already in general with value openshift
2015-10-26 13:50:02,674 - atomicapp.install - DEBUG - Component mlbparks-app is part of the app
2015-10-26 13:50:02,674 - atomicapp.install - DEBUG - Values: {u'mlbparks-app': {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}}
2015-10-26 13:50:02,674 - atomicapp.utils - INFO - atomicapp.status.info.message=All dependencies installed successfully.
2015-10-26 13:50:02,674 - atomicapp.install - DEBUG - {u'mlbparks-app': {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}}
2015-10-26 13:50:02,674 - atomicapp.nulecule_base - DEBUG - Data given {u'mlbparks-app': {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}}
2015-10-26 13:50:02,675 - atomicapp.install - DEBUG - {u'mlbparks-app': {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}, u'general': {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}}
2015-10-26 13:50:02,675 - atomicapp.utils - INFO - atomicapp.status.answer.message={"mlbparks-app": {"providerconfig": "/home/bos/mlamouri/.kube/config", "provider": "openshift"}, "general": {"providerconfig": "/home/bos/mlamouri/.kube/config", "provider": "openshift"}}
2015-10-26 13:50:02,675 - atomicapp.utils - INFO - atomicapp.status.info.message=Install Successful.
2015-10-26 13:50:02,675 - atomicapp.utils - INFO - atomicapp.status.info.message=Install Successful.
2015-10-26 13:50:02,675 - atomicapp.utils - DEBUG - Using working directory /atomicapp/.workdir
2015-10-26 13:50:02,676 - atomicapp.plugin - DEBUG - Loading providers from /usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/providers
2015-10-26 13:50:02,685 - atomicapp.nulecule_base - DEBUG - Setting app id to mlbparks-app
2015-10-26 13:50:02,685 - atomicapp.nulecule_base - DEBUG - Version check successful: specversion == 0.0.2
2015-10-26 13:50:02,685 - atomicapp.nulecule_base - DEBUG - Path to answers file given, loading /atomicapp/answers.conf
2015-10-26 13:50:02,685 - atomicapp.nulecule_base - DEBUG - Provider: openshift
2015-10-26 13:50:02,686 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://mongodb-template.json: OK.
2015-10-26 13:50:02,686 - atomicapp.utils - INFO - atomicapp.status.info.message=Artifact file://mlbparks-app-template.json: OK.
2015-10-26 13:50:02,686 - atomicapp.utils - INFO - atomicapp.status.info.message=All artifacts OK. 
2015-10-26 13:50:02,686 - atomicapp.nulecule_base - INFO - Artifacts for mlbparks-app present for these providers: openshift
2015-10-26 13:50:02,686 - atomicapp.utils - DEBUG - {u'artifacts': {u'openshift': [u'file://mongodb-template.json', u'file://mlbparks-app-template.json']}, u'name': u'mlbparks-app'}
2015-10-26 13:50:02,686 - atomicapp.run - DEBUG - Processing component 'mlbparks-app' and graph item '{u'artifacts': {u'openshift': [u'file://mongodb-template.json', u'file://mlbparks-app-template.json']}, u'name': u'mlbparks-app'}'
2015-10-26 13:50:02,686 - atomicapp.plugin - DEBUG - Found provider <class 'openshift.OpenShiftProvider'>
2015-10-26 13:50:02,687 - atomicapp.nulecule_base - DEBUG - Param providerconfig already in general with value /home/bos/mlamouri/.kube/config
2015-10-26 13:50:02,687 - atomicapp.nulecule_base - DEBUG - Param provider already in general with value openshift
2015-10-26 13:50:02,687 - atomicapp.utils - INFO - atomicapp.status.info.message=Deploying component mlbparks-app ...
2015-10-26 13:50:02,687 - atomicapp.run - INFO - Using provider openshift for component mlbparks-app
2015-10-26 13:50:02,738 - atomicapp.run - DEBUG - Templating artifact /atomicapp/mongodb-template.json
2015-10-26 13:50:02,738 - atomicapp.nulecule_base - DEBUG - Param providerconfig already in general with value /home/bos/mlamouri/.kube/config
2015-10-26 13:50:02,738 - atomicapp.nulecule_base - DEBUG - Param provider already in general with value openshift
2015-10-26 13:50:02,738 - atomicapp.run - DEBUG - Config: {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'} 
2015-10-26 13:50:02,738 - atomicapp.run - DEBUG - {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}
2015-10-26 13:50:02,748 - atomicapp.plugin - DEBUG - Writing artifact to /atomicapp/.workdir/mlbparks-app/mongodb-template.json
2015-10-26 13:50:02,814 - atomicapp.run - DEBUG - Templating artifact /atomicapp/mlbparks-app-template.json
2015-10-26 13:50:02,814 - atomicapp.nulecule_base - DEBUG - Param providerconfig already in general with value /home/bos/mlamouri/.kube/config
2015-10-26 13:50:02,814 - atomicapp.nulecule_base - DEBUG - Param provider already in general with value openshift
2015-10-26 13:50:02,815 - atomicapp.run - DEBUG - Config: {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'} 
2015-10-26 13:50:02,815 - atomicapp.run - DEBUG - {u'providerconfig': u'/home/bos/mlamouri/.kube/config', u'provider': u'openshift'}
2015-10-26 13:50:02,830 - atomicapp.plugin - DEBUG - Writing artifact to /atomicapp/.workdir/mlbparks-app/mlbparks-app-template.json
2015-10-26 13:50:02,831 - openshift - DEBUG - Using /host/usr/local/bin/oc to run OpenShift commands.
2015-10-26 13:50:02,831 - openshift - INFO - Processing template
2015-10-26 13:50:03,073 - openshift - DEBUG - Writing processed template to /atomicapp/.workdir/mlbparks-app/config-mongodb-template.json
2015-10-26 13:50:03,074 - openshift - INFO - Processing template
2015-10-26 13:50:03,285 - openshift - DEBUG - Writing processed template to /atomicapp/.workdir/mlbparks-app/config-mlbparks-app-template.json
buildconfig "mlbparks" created
imagestream "mlbparks" created
deploymentconfig "mlbparks" created
route "mlbparks-http-route" created
service "mlbparks-http" created
service "mlbparks-ping" created
```

**Comment by markllama** [comment] 2015-10-26 14:07
When the two templates are executed separately as __oc create -f <template_file>__ they successfully run the combined application, binding the mlb service to the database.

_NOTE:_ the autogenerated access variables must be provided explicitly

**Comment by markllama** [comment] 2015-10-26 14:36
This results in a working app: Note parameters provided to both so that generated parameters match.

# Create Database App
```
oc -p=APPLICATION_NAME=mlbparks,MONGODB_DATABASE=mlbapp,MONGODB_USER=mlbuser,MONGODB_PASSWORD=mlbpass,MONGODB_ADMIN_PASSWORD=mlbadminpass new-app -f mongodb-template.json
deploymentconfigs/mlbparks-mongodb
services/mongodb
Service "mongodb" created at 172.30.245.105 with port mappings 27017.
Run 'oc status' to view your app.
```

# Create MLB web app

```
oc -p=APPLICATION_NAME=mlbparks,MONGODB_DATABASE=mlbapp,MONGODB_USER=mlbuser,MONGODB_PASSWORD=mlbpass,MONGODB_ADMIN_PASSWORD=mlbadminpass new-app -f mlbparks-app-template.json
buildconfigs/mlbparks
imagestreams/mlbparks
deploymentconfigs/mlbparks
routes/mlbparks-http-route
services/mlbparks-http
services/mlbparks-ping
Build "mlbparks" created and started - you can run `oc status` to check the progress.
Service "mlbparks-http" created at 172.30.215.36 with port mappings 8080.
Service "mlbparks-ping" created at 172.30.254.224 with port mappings 8888.
Run 'oc status' to view your app.
```

**Comment by dustymabe** [comment] 2015-12-01 14:55
@kadel, do you mind looking at  this one too?

**Comment by kadel** [comment] 2015-12-01 15:11
yep, I have plans to look into this also.
I expect that we want to do this with openshift provider that uses api, right?
I have to dig deeper to openshift api, and find how to process templates with parameters.

**Comment by dustymabe** [comment] 2015-12-01 15:41
thanks!

**Comment by kadel** [comment] 2015-12-08 18:06
@markllama I have been working on openshift provider that is using OpenShift api - https://github.com/projectatomic/atomicapp/pull/420

I have been testing templates on your example. With that new provider it should be working ;-)
I just had to add parameters to Nulecule and artifacts (see https://github.com/kadel/openshift3mlbparks/commit/0a0c89ceba94b2ad1b999970590d92471fe5c8a4)

Only problem with that is that you need to be careful with naming variables/parameters. OpenShift and Nulecule parameters shouldn't have same names.

**Comment by kadel** [comment] 2015-12-15 12:27
I think we can close this. This should be fixed in new OpenShift provider.

**Comment by dustymabe** [comment] 2015-12-15 14:14
@markllama Do you possibly have time to verify this is fixed?

**Comment by dustymabe** [comment] 2015-12-18 15:29
ETIMEOUT.. @kadel do you mind trying this exact problem and verify it is fixed and then close this issue?

**Comment by kadel** [comment] 2016-01-05 13:58
I have been able to locate where the problem was.

at https://github.com/projectatomic/atomicapp/blob/0.2.3/atomicapp/providers/openshift.py#L118
Each artifact is added to `kube_order` with kind as key. So when there was multiple artifacts of same kind `kube_order[<kind>]` is overwritten each time and only last artifact of that kind is then processed.

I successfully reproduce this in version 0.2.3 and I also can confirm that this is no longer issue in 0.3.0

**Closed by kadel** 2016-01-05 13:58 UTC
Labels: bug, provider:openshift
